var template_content_characters = [];



template_content_characters.push('<div class="col-md-3" id="identity_panel">');
template_content_characters.push('        <div id="photo"></div>');
template_content_characters.push('        <div id="resume">');
template_content_characters.push('            <h2 class="var var-name%">Name</h2>');
template_content_characters.push('            <h3 class="var var-title%">Title of character</h3>');
template_content_characters.push('            <img src="../../assets/pictures/deaglan.png">');
template_content_characters.push('            <h3>Petits détails</h3>');
template_content_characters.push('            <ul class="facts_list">');
template_content_characters.push('                <li>');
template_content_characters.push('                    <span class="mini_fact_name">Vu en dernier</span>');
template_content_characters.push('                    <div class="fact "> Le 00 mois 000 à Sanctuaire, port-Ouestern<div>/');
template_content_characters.push('                </li>');
template_content_characters.push('                <li>');
template_content_characters.push('                    <span class="mini_fact_name">Habite à</span>');
template_content_characters.push('                    <div class="fact"> Sanctuaire, port-Ouestern</div>');
template_content_characters.push('                </li>');
template_content_characters.push('            </ul>');
template_content_characters.push('        </div>');
template_content_characters.push('    </div>');
template_content_characters.push('    <div class="col-md-9" id="information_panels">');
template_content_characters.push('        <div class="row">');
template_content_characters.push('            <div class="col-md-6 description physical">');
template_content_characters.push('                <h3>Description physique</h3>');
template_content_characters.push('                <p class="var var-physical%">');
template_content_characters.push('                Etiam id magna et ligula ultricies dapibus et sed lectus. ')
template_content_characters.push('                </p>');
template_content_characters.push('            </div>');
template_content_characters.push('            <div class="col-md-6 description mental">');
template_content_characters.push('                <h3>Description morale</h3>');
template_content_characters.push('                <p class="var var-mental%">');
template_content_characters.push('                Quisque sed est a mauris feugiat laoreet. Praesent lacinia suscipit ');
template_content_characters.push('                </p>');
template_content_characters.push('            </div>');
template_content_characters.push('        </div>');
template_content_characters.push('        <h3>Détails connus</h3>');
template_content_characters.push('        <ul class="row facts_list" id="facts">');
template_content_characters.push('            <li>');
template_content_characters.push('                <span type="button"');
template_content_characters.push('                      class="btn btn-default btn-xs"');
template_content_characters.push('                      data-toggle="collapse"');
template_content_characters.push('                      data-target="#fact_content">');
template_content_characters.push('                    <i class="fa fa-plus" aria-hidden="true"></i>');
template_content_characters.push('                </span>');
template_content_characters.push('                <span>fact name</span>');
template_content_characters.push('                <div id="fact_content" class="collapse fact">Mauris commodo sed lacus sed vehicula. Quisque metus dui, maximus nec neque quis, cursus fringilla enim. Nullam fermentum enim nibh, sit amet tempus neque tincidunt et. Maecenas lectus enim, aliquam ac elit et, imperdiet accumsan libero. Suspendisse eu mi a elit volutpat posuere. Nunc non dui et purus fringilla elementum ut auctor urna. Etiam molestie ligula et velit gravida, eleifend egestas sapien tristique. Duis tempus justo est, ut tempor lectus malesuada quis.</div>');
template_content_characters.push('            </li>');
template_content_characters.push('            <li>');
template_content_characters.push('                <span type="button"');
template_content_characters.push('                      class="btn btn-default btn-xs"');
template_content_characters.push('                      data-toggle="collapse"');
template_content_characters.push('                      data-target="#fact_content2">');
template_content_characters.push('                    <i class="fa fa-plus" aria-hidden="true"></i>');
template_content_characters.push('                </span>');
template_content_characters.push('                <span>fact name</span>');
template_content_characters.push('                <div id="fact_content2" class="collapse fact">Mauris commodo sed lacus sed vehicula. Quisque metus dui, maximus nec neque quis, cursus fringilla enim. Nullam fermentum enim nibh, sit amet tempus neque tincidunt et. Maecenas lectus enim, aliquam ac elit et, imperdiet accumsan libero. Suspendisse eu mi a elit volutpat posuere. Nunc non dui et purus fringilla elementum ut auctor urna. Etiam molestie ligula et velit gravida, eleifend egestas sapien tristique. Duis tempus justo est, ut tempor lectus malesuada quis.</div>');
template_content_characters.push('            </li>');
template_content_characters.push('            <li>');
template_content_characters.push('                <span type="button"');
template_content_characters.push('                      class="btn btn-default btn-xs"');
template_content_characters.push('                      data-toggle="collapse"');
template_content_characters.push('                      data-target="#fact_content3">');
template_content_characters.push('                    <i class="fa fa-plus" aria-hidden="true"></i>');
template_content_characters.push('                </span>');
template_content_characters.push('                <span>fact name</span>');
template_content_characters.push('                <div id="fact_content3" class="collapse fact">Mauris commodo sed lacus sed vehicula. Quisque metus dui, maximus nec neque quis, cursus fringilla enim. Nullam fermentum enim nibh, sit amet tempus neque tincidunt et. Maecenas lectus enim, aliquam ac elit et, imperdiet accumsan libero. Suspendisse eu mi a elit volutpat posuere. Nunc non dui et purus fringilla elementum ut auctor urna. Etiam molestie ligula et velit gravida, eleifend egestas sapien tristique. Duis tempus justo est, ut tempor lectus malesuada quis.</div>');
template_content_characters.push('            </li>');
template_content_characters.push('        </ul>');
template_content_characters.push('     </div>');